spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/policy_service
    username: postgres
    password: 4556
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: policy-service-group
server:
  port: 8082